package com.teamdexters.limitless.ui.roommapping

import android.os.Build
import android.os.VibrationEffect
import android.os.Vibrator
import android.os.VibratorManager
import android.speech.tts.TextToSpeech
import android.graphics.BitmapFactory
import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.LazyRow
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.runtime.collectAsState
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.teamdexters.limitless.roommapping.RoomPhotoCapture
import com.teamdexters.limitless.roommapping.RoomSpatialAiAnalyzer
import com.teamdexters.limitless.roommapping.SpatialRouteResult
import com.teamdexters.limitless.roommapping.LiveNavigationEngine
import com.teamdexters.limitless.ui.components.SafeCircularProgressIndicator
import kotlinx.coroutines.launch
import java.io.File
import java.util.Locale

@Composable
fun PhotoRouteScreen(
    roomId: String,
    photoPaths: List<String>,
    onRouteSaved: () -> Unit
) {
    val context = LocalContext.current
    val coroutineScope = rememberCoroutineScope()
    val analyzer = remember { RoomSpatialAiAnalyzer(context) }
    val photoCaptureUtil = remember { RoomPhotoCapture(context) }

    var result by remember { mutableStateOf<SpatialRouteResult?>(null) }
    var isLoading by remember { mutableStateOf(true) }
    var ttsReady by remember { mutableStateOf(false) }
    val tts = remember {
        lateinit var ttsObj: TextToSpeech
        ttsObj = TextToSpeech(context) { status ->
            if (status == TextToSpeech.SUCCESS) {
                ttsObj.language = Locale.US
                ttsReady = true
                android.util.Log.d("LIMITLESS_TRACE", "TTS initialized successfully")
            } else {
                android.util.Log.e("LIMITLESS_TRACE", "TTS initialization failed with status $status")
            }
        }
        ttsObj
    }
    
    val navEngine = remember { LiveNavigationEngine(context) }
    val isNavigating by navEngine.isNavigating.collectAsState()
    val currentStepIndex by navEngine.currentStepIndex.collectAsState()

    DisposableEffect(Unit) {
        onDispose { 
            tts.shutdown() 
            navEngine.shutdown()
        }
    }

    LaunchedEffect(roomId) {
        coroutineScope.launch {
            isLoading = true
            result = analyzer.analyzeMultiAnglePhotos(roomId, photoPaths)
            isLoading = false

            result?.let {
                if (ttsReady) {
                    tts.speak("Auto-generated walking route ready. ${it.autoGeneratedRouteSteps.size} steps calculated.", TextToSpeech.QUEUE_FLUSH, null, null)
                }
            }
        }
    }

    Box(
        modifier = Modifier
            .fillMaxSize()
            .background(Color(0xFFF7F1EE))
            .padding(16.dp)
    ) {
        if (isLoading) {
            Column(
                modifier = Modifier.fillMaxSize(),
                horizontalAlignment = Alignment.CenterHorizontally,
                verticalArrangement = Arrangement.Center
            ) {
                SafeCircularProgressIndicator(size = 48.dp, color = Color(0xFFF791A9))
                Spacer(modifier = Modifier.height(16.dp))
                Text(
                    text = "Generating 3D Spatial Route from Multi-Angle Photos...",
                    color = Color(0xFF1F1F1F),
                    fontSize = 16.sp,
                    fontWeight = FontWeight.Bold
                )
            }
        } else {
            result?.let { spatial ->
                LazyColumn(
                    modifier = Modifier.fillMaxSize(),
                    verticalArrangement = Arrangement.spacedBy(16.dp)
                ) {
                    // Header Status Banner
                    item {
                        val bannerColor = when (spatial.overallSafetyRating) {
                            "CLEAR" -> Color(0xFFBAD6DA)
                            "PARTIALLY_CLEAR" -> Color(0xFFDDDD7B)
                            else -> Color(0xFFF791A9)
                        }

                        Card(
                            colors = CardDefaults.cardColors(containerColor = Color(0xFFE0F2F4)),
                            shape = RoundedCornerShape(12.dp),
                            modifier = Modifier
                                .fillMaxWidth()
                                .border(2.dp, bannerColor, RoundedCornerShape(12.dp))
                        ) {
                            Column(modifier = Modifier.padding(16.dp)) {
                                Text(
                                    text = "PATH SAFETY: ${spatial.overallSafetyRating}",
                                    color = Color(0xFF1F1F1F),
                                    fontSize = 18.sp,
                                    fontWeight = FontWeight.Bold
                                )
                                Spacer(modifier = Modifier.height(4.dp))
                                Text(
                                    text = spatial.aiSpatialSummary,
                                    color = Color(0xFF1F1F1F),
                                    fontSize = 14.sp
                                )
                            }
                        }
                    }

                    // 3D Isometric Map
                    item {
                        Card(
                            modifier = Modifier.fillMaxWidth().height(260.dp),
                            shape = RoundedCornerShape(16.dp),
                            colors = CardDefaults.cardColors(containerColor = Color(0xFFE0F2F4))
                        ) {
                            Box(modifier = Modifier.fillMaxSize()) {
                                ThreeDIsometricMap(
                                    routeResult = spatial,
                                    activeStepIndex = currentStepIndex
                                )
                            }
                        }
                    }

                    // Multi-Angle Photo Thumbnails
                    item {
                        Text(
                            text = "Multi-Angle Captured Space",
                            fontSize = 16.sp,
                            fontWeight = FontWeight.Bold,
                            color = Color(0xFF1F1F1F)
                        )
                        Spacer(modifier = Modifier.height(8.dp))
                        LazyRow(horizontalArrangement = Arrangement.spacedBy(12.dp)) {
                            items(photoPaths) { path ->
                                val bitmap = remember(path) {
                                    val file = File(path)
                                    if (file.exists()) BitmapFactory.decodeFile(file.absolutePath) else null
                                }
                                Box(
                                    modifier = Modifier
                                        .size(100.dp)
                                        .clip(RoundedCornerShape(8.dp))
                                        .background(Color(0xFFE0F2F4))
                                ) {
                                    bitmap?.let {
                                        Image(
                                            bitmap = it.asImageBitmap(),
                                            contentDescription = "Angle photo",
                                            modifier = Modifier.fillMaxSize(),
                                            contentScale = ContentScale.Crop
                                        )
                                    }
                                }
                            }
                        }
                    }

                    // Auto-Generated Route Steps Header
                    item {
                        Text(
                            text = "Auto-Generated Walking Route",
                            fontSize = 18.sp,
                            fontWeight = FontWeight.Bold,
                            color = Color(0xFF1F1F1F)
                        )
                    }

                    // Route Steps List
                    items(spatial.autoGeneratedRouteSteps) { step ->
                        Card(
                            colors = CardDefaults.cardColors(containerColor = Color(0xFFE0F2F4)),
                            shape = RoundedCornerShape(12.dp),
                            modifier = Modifier.fillMaxWidth()
                        ) {
                            Row(
                                modifier = Modifier.padding(16.dp),
                                verticalAlignment = Alignment.CenterVertically
                            ) {
                                Box(
                                    modifier = Modifier
                                        .size(36.dp)
                                        .background(Color(0xFFF791A9), RoundedCornerShape(18.dp)),
                                    contentAlignment = Alignment.Center
                                ) {
                                    Text(
                                        text = "${step.stepIndex}",
                                        color = Color.White,
                                        fontWeight = FontWeight.Bold
                                    )
                                }
                                Spacer(modifier = Modifier.width(16.dp))
                                Column {
                                    Text(
                                        text = step.instructionText,
                                        color = Color(0xFF1F1F1F),
                                        fontWeight = FontWeight.Bold,
                                        fontSize = 15.sp
                                    )
                                    Spacer(modifier = Modifier.height(2.dp))
                                    Text(
                                        text = "Landmark: ${step.landmarkReference}",
                                        color = Color(0xFF1F1F1F),
                                        fontSize = 13.sp
                                    )
                                }
                            }
                        }
                    }

                    // Action Buttons Row
                    item {
                        Column(verticalArrangement = Arrangement.spacedBy(12.dp)) {
                            if (isNavigating) {
                                Row(
                                    modifier = Modifier.fillMaxWidth(),
                                    horizontalArrangement = Arrangement.spacedBy(8.dp)
                                ) {
                                    Button(
                                        onClick = { navEngine.previousStep() },
                                        colors = ButtonDefaults.buttonColors(containerColor = Color(0xFFBAD6DA)),
                                        modifier = Modifier.weight(1f).height(50.dp),
                                        shape = RoundedCornerShape(12.dp)
                                    ) {
                                        Text("◀ Prev", color = Color(0xFF1F1F1F), fontWeight = FontWeight.Bold)
                                    }
                                    Button(
                                        onClick = { navEngine.stopNavigation() },
                                        colors = ButtonDefaults.buttonColors(containerColor = Color(0xFFF791A9)),
                                        modifier = Modifier.weight(1f).height(50.dp),
                                        shape = RoundedCornerShape(12.dp)
                                    ) {
                                        Text("Stop", color = Color.White, fontWeight = FontWeight.Bold)
                                    }
                                    Button(
                                        onClick = { navEngine.nextStep() },
                                        colors = ButtonDefaults.buttonColors(containerColor = Color(0xFF00C853)),
                                        modifier = Modifier.weight(1f).height(50.dp),
                                        shape = RoundedCornerShape(12.dp)
                                    ) {
                                        Text("Next ▶", color = Color.White, fontWeight = FontWeight.Bold)
                                    }
                                }
                            } else {
                                Button(
                                    onClick = { navEngine.startNavigation(spatial.autoGeneratedRouteSteps) },
                                    colors = ButtonDefaults.buttonColors(containerColor = Color(0xFF00C853)),
                                    modifier = Modifier.fillMaxWidth().height(50.dp),
                                    shape = RoundedCornerShape(12.dp)
                                ) {
                                    Text("▶ Start Live 3D Navigation", color = Color.White, fontWeight = FontWeight.Bold)
                                }
                            }

                            Button(
                                onClick = {
                                    val fullRouteSpeech = spatial.autoGeneratedRouteSteps.joinToString(". ") { it.instructionText }
                                    if (ttsReady) {
                                        tts.speak("Full route: $fullRouteSpeech", TextToSpeech.QUEUE_FLUSH, null, null)
                                    }

                                    val vibrator = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
                                        val vibratorManager = context.getSystemService(android.content.Context.VIBRATOR_MANAGER_SERVICE) as VibratorManager
                                        vibratorManager.defaultVibrator
                                    } else {
                                        @Suppress("DEPRECATION")
                                        context.getSystemService(android.content.Context.VIBRATOR_SERVICE) as Vibrator
                                    }
                                    vibrator.vibrate(VibrationEffect.createOneShot(200, VibrationEffect.DEFAULT_AMPLITUDE))
                                },
                                colors = ButtonDefaults.buttonColors(containerColor = Color(0xFFFFE797)),
                                modifier = Modifier.fillMaxWidth().height(50.dp),
                                shape = RoundedCornerShape(12.dp)
                            ) {
                                Text("🔊 Speak Walking Route Aloud", color = Color(0xFF1F1F1F), fontWeight = FontWeight.Bold)
                            }

                            Button(
                                onClick = onRouteSaved,
                                colors = ButtonDefaults.buttonColors(containerColor = Color(0xFFF791A9)),
                                modifier = Modifier.fillMaxWidth().height(50.dp),
                                shape = RoundedCornerShape(12.dp)
                            ) {
                                Text("💾 Save Room & Auto-Route to DB", color = Color.White, fontWeight = FontWeight.Bold)
                            }
                        }
                        Spacer(modifier = Modifier.height(100.dp))
                    }
                }
            }
        }
    }
}
