package com.teamdexters.limitless.ui.roommapping

import androidx.compose.animation.core.*
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.gestures.detectTransformGestures
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.geometry.Size
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.Path
import androidx.compose.ui.graphics.drawscope.Stroke
import androidx.compose.ui.graphics.drawscope.withTransform
import androidx.compose.ui.input.pointer.pointerInput
import com.teamdexters.limitless.roommapping.SpatialRouteResult

@Composable
fun ThreeDIsometricMap(
    routeResult: SpatialRouteResult,
    activeStepIndex: Int = 0,
    modifier: Modifier = Modifier
) {
    var scale by remember { mutableStateOf(1f) }
    var offset by remember { mutableStateOf(Offset.Zero) }

    val infiniteTransition = rememberInfiniteTransition()
    val pulseAlpha by infiniteTransition.animateFloat(
        initialValue = 0.3f,
        targetValue = 1f,
        animationSpec = infiniteRepeatable(
            animation = tween(1000, easing = LinearEasing),
            repeatMode = RepeatMode.Reverse
        )
    )

    Canvas(
        modifier = modifier
            .fillMaxSize()
            .pointerInput(Unit) {
                detectTransformGestures { _, pan, zoom, _ ->
                    scale = (scale * zoom).coerceIn(0.5f, 3f)
                    offset += pan
                }
            }
    ) {
        withTransform({
            translate(offset.x, offset.y)
            scale(scale, scale)
            translate(size.width / 2, size.height / 2)
            rotate(45f)
            scale(1f, 0.5f)
            translate(-size.width / 2, -size.height / 2)
        }) {
            val gridSpacing = 60f
            val roomWidth = size.width * 0.8f
            val roomHeight = size.height * 0.8f
            val startX = (size.width - roomWidth) / 2
            val startY = (size.height - roomHeight) / 2

            for (x in 0..roomWidth.toInt() step gridSpacing.toInt()) {
                drawLine(
                    color = Color.LightGray.copy(alpha = 0.3f),
                    start = Offset(startX + x, startY),
                    end = Offset(startX + x, startY + roomHeight),
                    strokeWidth = 2f
                )
            }
            for (y in 0..roomHeight.toInt() step gridSpacing.toInt()) {
                drawLine(
                    color = Color.LightGray.copy(alpha = 0.3f),
                    start = Offset(startX, startY + y),
                    end = Offset(startX + roomWidth, startY + y),
                    strokeWidth = 2f
                )
            }

            drawRect(
                color = Color(0xFF1F1F1F),
                topLeft = Offset(startX, startY),
                size = Size(roomWidth, roomHeight),
                style = Stroke(width = 8f)
            )

            val waypoints = mutableListOf<Offset>()
            val stepsCount = if (routeResult.autoGeneratedRouteSteps.isEmpty()) 3 else routeResult.autoGeneratedRouteSteps.size
            
            waypoints.add(Offset(startX + roomWidth * 0.5f, startY + roomHeight * 0.9f))
            if (stepsCount > 1) {
                for (i in 1 until stepsCount) {
                    val progress = i.toFloat() / stepsCount
                    waypoints.add(Offset(startX + roomWidth * (0.5f - progress * 0.3f), startY + roomHeight * (0.9f - progress * 0.7f)))
                }
            }

            if (waypoints.size >= 2) {
                val path = Path().apply {
                    moveTo(waypoints.first().x, waypoints.first().y)
                    for (i in 1 until waypoints.size) {
                        lineTo(waypoints[i].x, waypoints[i].y)
                    }
                }
                drawPath(
                    path = path,
                    color = Color(0xFFF791A9),
                    style = Stroke(width = 10f)
                )
            }

            waypoints.forEachIndexed { index, point ->
                val isActive = index == activeStepIndex
                drawCircle(
                    color = if (isActive) Color(0xFF00C853).copy(alpha = pulseAlpha) else Color(0xFFBAD6DA),
                    radius = if (isActive) 25f else 15f,
                    center = point
                )
            }
        }
    }
}
