package com.teamdexters.limitless.data.local.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Entity representing an AI-analyzed accessibility score for a building.
 * Generated from ML Kit image analysis and computer vision.
 */
@Entity(tableName = "accessibility_scores")
data class AccessibilityScoreEntity(
    /**
     * Primary key for the accessibility score record.
     * Auto-generated by Room database.
     */
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,

    /**
     * Name of the building or location analyzed.
     * Examples: "Academic Block A", "Student Center", "Sports Complex"
     */
    val buildingName: String,

    /**
     * Computed weighted accessibility score (0 to 100).
     * Higher scores indicate better accessibility.
     * Calculated from individual feature scores.
     */
    val overallScore: Int,

    /**
     * Indicates whether a ramp was detected in the analysis.
     */
    val rampDetected: Boolean,

    /**
     * Indicates whether stairs were detected in the analysis.
     */
    val stairsDetected: Boolean,

    /**
     * Indicates whether handrails were detected in the analysis.
     */
    val handrailsDetected: Boolean,

    /**
     * Estimated relative door width score.
     * Higher values indicate wider, more accessible doors.
     */
    val doorWidthScore: Float,

    /**
     * Lighting analysis score.
     * Higher values indicate better lighting conditions.
     */
    val lightingScore: Float,

    /**
     * Indicates whether braille signage was detected.
     */
    val brailleSignagePresent: Boolean,

    /**
     * Indicates whether an accessible washroom was detected.
     */
    val accessibleWashroomPresent: Boolean,

    /**
     * Local file path to the analyzed photo.
     * Null if no photo was analyzed.
     */
    val photoUri: String?,

    /**
     * Indicates whether the location score has been verified by the Limitless Team.
     */
    val isTeamVerified: Boolean = false,

    /**
     * Synchronization status with remote database (Supabase).
     * Valid values: "PENDING", "SYNCED", "FAILED"
     * Default value is "PENDING" (not yet synced).
     */
    val syncStatus: String = "PENDING",

    /**
     * Timestamp when the analysis was performed.
     * Default value is current system time in milliseconds.
     */
    val timestamp: Long = System.currentTimeMillis()
)