package com.teamdexters.limitless.data.local.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Entity representing a user-reported accessibility issue or feature.
 * Used for crowd-sourced accessibility data collection.
 */
@Entity(tableName = "user_reports")
data class UserReportEntity(
    /**
     * Primary key for the report.
     * Auto-generated by Room database.
     */
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,

    /**
     * Name of the place or building being reported.
     * Examples: "Central Library", "Metro Station", "Shopping Mall"
     */
    val locationName: String,

    /**
     * Geographic latitude coordinate of the reported location.
     * Used for mapping and location-based queries.
     */
    val latitude: Double,

    /**
     * Geographic longitude coordinate of the reported location.
     * Used for mapping and location-based queries.
     */
    val longitude: Double,

    /**
     * Category of the accessibility feature or issue.
     * Valid values: "RAMP", "ELEVATOR", "RESTROOM", "ENTRANCE", "OBSTACLE"
     */
    val category: String,

    /**
     * User notes or quick-tag selections describing the accessibility aspect.
     * Free-text field for additional context.
     */
    val description: String,

    /**
     * Indicates whether a ramp is available at this location.
     */
    val hasRamp: Boolean,

    /**
     * Indicates whether an elevator is available at this location.
     */
    val hasElevator: Boolean,

    /**
     * Indicates whether an accessible restroom is available at this location.
     */
    val hasAccessibleRestroom: Boolean,

    /**
     * Local file path to photo evidence of the accessibility feature.
     * Null if no photo was provided.
     */
    val photoUri: String?,

    /**
     * Trust score based on upvotes/confirmations from other users.
     * Higher values indicate more reliable reports.
     * Default value is 1 (initial report).
     */
    val trustScore: Int = 1,

    /**
     * Trust score based on upvotes/confirmations from other users.
     * Higher values indicate more reliable reports.
     * Default value is 1 (initial report).
     */
    val confirmationCount: Int = 1,

    /**
     * Synchronization status with remote database (Supabase).
     * Valid values: "PENDING", "SYNCED", "FAILED"
     * Default value is "PENDING" (not yet synced).
     */
    val syncStatus: String = "PENDING",

    /**
     * Timestamp when the report was created.
     * Default value is current system time in milliseconds.
     */
    val timestamp: Long = System.currentTimeMillis()
)